import type { Rarity } from "./rarity";

export type GachaCategoryId = "love" | "money" | "work" | "relations" | "abyss";

export type GachaCategory = {
  id: GachaCategoryId;
  name: string;
  shortName: string;
  icon: string;
  tone: string;
  description: string;
};

export type FortuneResult = {
  id: string;
  category: GachaCategoryId;
  rarity: Rarity;
  title: string;
  body: string;
  luckyItem: string;
  luckyColor: string;
  word: string;
};

export const categories: GachaCategory[] = [
  {
    id: "love",
    name: "恋愛運ガチャ",
    shortName: "恋愛",
    icon: "heart",
    tone: "from-rose-400 to-fuchsia-500",
    description: "言葉にならない距離感を読み解く",
  },
  {
    id: "money",
    name: "金運ガチャ",
    shortName: "金運",
    icon: "coin",
    tone: "from-amber-300 to-lime-400",
    description: "巡る対価と小さな豊かさの兆し",
  },
  {
    id: "work",
    name: "仕事運ガチャ",
    shortName: "仕事",
    icon: "blade",
    tone: "from-cyan-300 to-indigo-400",
    description: "選択、集中、評価の流れを占う",
  },
  {
    id: "relations",
    name: "人間関係ガチャ",
    shortName: "関係",
    icon: "moon",
    tone: "from-emerald-300 to-teal-500",
    description: "結び目と沈黙の温度を見る",
  },
  {
    id: "abyss",
    name: "深淵ガチャ",
    shortName: "深淵",
    icon: "eye",
    tone: "from-violet-400 to-slate-200",
    description: "覗いたものに、覗き返される",
  },
];

export const fortuneResults: FortuneResult[] = [
  {
    id: "love-n-1",
    category: "love",
    rarity: "N",
    title: "静かな灯",
    body: "今日は無理に距離を詰めるより、相手の反応をひとつ丁寧に拾う日です。焦らない態度が、思った以上に印象を残します。",
    luckyItem: "透明なリップ",
    luckyColor: "薄藤",
    word: "返事より余韻を信じて。",
  },
  {
    id: "love-n-2",
    category: "love",
    rarity: "N",
    title: "既読の星",
    body: "見えないところで気持ちは少し動いています。派手な進展はなくても、あなたの自然な一言が流れを整えます。",
    luckyItem: "小さな鏡",
    luckyColor: "ミルキーピンク",
    word: "軽い言葉ほど届く日。",
  },
  {
    id: "love-n-3",
    category: "love",
    rarity: "N",
    title: "眠る花冠",
    body: "相手に合わせすぎると、あなた本来の魅力が隠れます。今日は少しだけ自分の予定を優先すると、空気が澄みます。",
    luckyItem: "ハーブティー",
    luckyColor: "シェルホワイト",
    word: "待つことも選択です。",
  },
  {
    id: "love-r-1",
    category: "love",
    rarity: "R",
    title: "月下の合図",
    body: "偶然の会話や小さな接点に、次の扉が混ざっています。気になる人には完璧な言葉より、短く素直な反応が効きます。",
    luckyItem: "シルバーリング",
    luckyColor: "ローズグレー",
    word: "目線は嘘をつきにくい。",
  },
  {
    id: "love-r-2",
    category: "love",
    rarity: "R",
    title: "微熱のカード",
    body: "自分でも説明できない期待が増えそうです。ただし深読みしすぎると運が散ります。今は一歩だけ近づくのが正解。",
    luckyItem: "ミントガム",
    luckyColor: "ラズベリー",
    word: "少し残すほど惹かれる。",
  },
  {
    id: "love-r-3",
    category: "love",
    rarity: "R",
    title: "告白前夜",
    body: "心の中で保留にしていたことが、表情に出やすい日です。隠すより、やわらかく出した方が関係は進みます。",
    luckyItem: "香りのあるハンドクリーム",
    luckyColor: "ワインレッド",
    word: "照れは弱点ではなく鍵。",
  },
  {
    id: "love-sr-1",
    category: "love",
    rarity: "SR",
    title: "星鍵の再会",
    body: "過去の会話や忘れていた縁が、今のあなたに別の意味を持って戻ります。連絡するなら、理由は軽くて構いません。",
    luckyItem: "古い写真",
    luckyColor: "アメジスト",
    word: "再開は偶然の顔をして来る。",
  },
  {
    id: "love-sr-2",
    category: "love",
    rarity: "SR",
    title: "反転する鼓動",
    body: "遠く感じていた相手ほど、実はあなたを気にしている気配があります。今日は沈黙を恐れず、間を味方につけて。",
    luckyItem: "黒いノート",
    luckyColor: "ディープマゼンタ",
    word: "言わない時間が育てるものもある。",
  },
  {
    id: "love-sr-3",
    category: "love",
    rarity: "SR",
    title: "甘い予兆",
    body: "魅力がいつもより強く伝わります。背伸びした演出より、少し無防備な本音が相手の記憶に残るでしょう。",
    luckyItem: "月モチーフのアクセサリー",
    luckyColor: "プラム",
    word: "今日は隙が光になります。",
  },
  {
    id: "love-ssr-1",
    category: "love",
    rarity: "SSR",
    title: "運命反転の接吻",
    body: "停滞していた感情が、近いうちに向きを変えます。小さな違和感を見逃さないでください。それは関係が動く前のノイズです。",
    luckyItem: "紫のキャンドル",
    luckyColor: "ロイヤルパープル",
    word: "心が先に扉を開けます。",
  },
  {
    id: "love-ssr-2",
    category: "love",
    rarity: "SSR",
    title: "禁書のラブレター",
    body: "まだ言葉になっていない想いが、相手の態度に滲みます。駆け引きよりも、あなたの誠実な一手が空気を変えます。",
    luckyItem: "封筒",
    luckyColor: "ノクターンブルー",
    word: "本命ほど静かに近づく。",
  },
  {
    id: "love-ssr-3",
    category: "love",
    rarity: "SSR",
    title: "夜明けの誓約",
    body: "関係の名前が変わる前触れがあります。期待しすぎず、でも逃げないで。今のあなたには受け取る力があります。",
    luckyItem: "星柄の布",
    luckyColor: "シャンパンゴールド",
    word: "選ばれる準備をして。",
  },
  {
    id: "love-ur-1",
    category: "love",
    rarity: "UR",
    title: "選ばれなかった未来の恋",
    body: "あなたの選ばなかった未来が、もう一度扉を叩いています。偶然に見える出来事ほど、今は意味を持ちます。",
    luckyItem: "鍵のチャーム",
    luckyColor: "虹を含む黒",
    word: "運命は二度、同じ顔で現れない。",
  },
  {
    id: "love-ur-2",
    category: "love",
    rarity: "UR",
    title: "神託級ハートブレイク",
    body: "終わったと思った感情に、祝福のような再起動が入ります。怖さごと抱えて進む時、恋はあなたの味方になります。",
    luckyItem: "赤い糸",
    luckyColor: "オーロラローズ",
    word: "壊れた場所から光が漏れる。",
  },
  {
    id: "love-ur-3",
    category: "love",
    rarity: "UR",
    title: "双月の契約",
    body: "相手とあなたのタイミングが、珍しく重なり始めています。今日は素直さが最強の魔法です。遠回りした分だけ深く届きます。",
    luckyItem: "ペアのもの",
    luckyColor: "月光金",
    word: "言葉にした瞬間、世界線が寄る。",
  },
  {
    id: "money-n-1",
    category: "money",
    rarity: "N",
    title: "小銭の守護",
    body: "大きく増やすより、漏れを止めることで運が整います。今日は買う前に一度だけ時間を置くと、財布が守られます。",
    luckyItem: "レシート入れ",
    luckyColor: "サンドベージュ",
    word: "残すことも稼ぐこと。",
  },
  {
    id: "money-n-2",
    category: "money",
    rarity: "N",
    title: "財布の月齢",
    body: "必要な支出と気分の支出を分けると、金運の流れが見えます。小さな整理が、次の余裕を呼びます。",
    luckyItem: "布製ポーチ",
    luckyColor: "オリーブ",
    word: "数字を見るほど不安は薄まる。",
  },
  {
    id: "money-n-3",
    category: "money",
    rarity: "N",
    title: "倹約の灯台",
    body: "今日は派手な勝負より、地味な見直しが吉です。サブスクや買い置きの確認に、思わぬ発見があります。",
    luckyItem: "白いメモ",
    luckyColor: "アイボリー",
    word: "静かな節約が未来を作る。",
  },
  {
    id: "money-r-1",
    category: "money",
    rarity: "R",
    title: "巡る硬貨",
    body: "誰かに渡した親切が、別の形で戻りやすい日です。損得だけで測らない選択に、後から小さな得がつきます。",
    luckyItem: "五円玉",
    luckyColor: "ブラスゴールド",
    word: "流したものほど戻る。",
  },
  {
    id: "money-r-2",
    category: "money",
    rarity: "R",
    title: "宝箱の鍵穴",
    body: "欲しかったものの代替案に運があります。少し視点をずらすと、満足度の高い選択肢が見つかりそうです。",
    luckyItem: "価格比較アプリ",
    luckyColor: "ピーコックグリーン",
    word: "安さより納得を選んで。",
  },
  {
    id: "money-r-3",
    category: "money",
    rarity: "R",
    title: "黄金の余白",
    body: "予定外の出費はありますが、必要な未来への通行料です。使う理由を言葉にできるなら、恐れすぎなくて大丈夫。",
    luckyItem: "黒い財布",
    luckyColor: "ハニーイエロー",
    word: "使い方に品格が宿る。",
  },
  {
    id: "money-sr-1",
    category: "money",
    rarity: "SR",
    title: "増幅する対価",
    body: "過去に積んだ経験が、収入や評価につながる兆しがあります。自分の得意を安く見積もらないことが鍵です。",
    luckyItem: "名刺",
    luckyColor: "エメラルド",
    word: "価値は先に自分が認める。",
  },
  {
    id: "money-sr-2",
    category: "money",
    rarity: "SR",
    title: "星屑の利息",
    body: "少額でも未来に回す行動が強い日です。学び、道具、環境への投資は、あとで意外な形で効いてきます。",
    luckyItem: "新しいペン",
    luckyColor: "スターゴールド",
    word: "種まきは静かに勝つ。",
  },
  {
    id: "money-sr-3",
    category: "money",
    rarity: "SR",
    title: "金脈の囁き",
    body: "見落としていた収入源や交換条件に気づけそうです。面倒で後回しにした確認ほど、今日は価値があります。",
    luckyItem: "通帳アプリ",
    luckyColor: "ティール",
    word: "眠る数字を起こして。",
  },
  {
    id: "money-ssr-1",
    category: "money",
    rarity: "SSR",
    title: "財運反転の魔法陣",
    body: "止まっていたお金の流れに、反転の兆しがあります。小さな交渉や条件変更が、長く効く結果を連れてきます。",
    luckyItem: "金色のクリップ",
    luckyColor: "オールドゴールド",
    word: "受け取る器を広げて。",
  },
  {
    id: "money-ssr-2",
    category: "money",
    rarity: "SSR",
    title: "黒曜の宝冠",
    body: "価値あるものを見抜く直感が冴えます。安易な衝動買いではなく、長く使える一品に運が宿ります。",
    luckyItem: "革小物",
    luckyColor: "黒曜石",
    word: "本物は静かに残る。",
  },
  {
    id: "money-ssr-3",
    category: "money",
    rarity: "SSR",
    title: "契約の星雨",
    body: "条件が噛み合う話が近づいています。返事を急がず、細部を読むほどあなたに有利な形が見えます。",
    luckyItem: "チェックリスト",
    luckyColor: "プラチナ",
    word: "細部に金運が隠れる。",
  },
  {
    id: "money-ur-1",
    category: "money",
    rarity: "UR",
    title: "禁断金脈 解放",
    body: "あなたが見過ごしていた価値が、急に輪郭を持ちます。偶然の紹介、古いスキル、眠っていた物に豊かさの入口があります。",
    luckyItem: "古い道具",
    luckyColor: "虹金",
    word: "財は気づいた瞬間から流れ込む。",
  },
  {
    id: "money-ur-2",
    category: "money",
    rarity: "UR",
    title: "黄金竜の目覚め",
    body: "守りの運と攻めの運が同時に立ち上がります。怖くても、正当に求めることを避けないでください。",
    luckyItem: "ゴールドカードケース",
    luckyColor: "ドラゴンゴールド",
    word: "遠慮は今日は封印。",
  },
  {
    id: "money-ur-3",
    category: "money",
    rarity: "UR",
    title: "星貨降臨",
    body: "お金にまつわる思い込みが書き換わる日です。受け取ることへの罪悪感を手放すほど、巡りは速くなります。",
    luckyItem: "水晶の置物",
    luckyColor: "オーロライエロー",
    word: "豊かさは許可から始まる。",
  },
  {
    id: "work-n-1",
    category: "work",
    rarity: "N",
    title: "机上の結界",
    body: "新しい挑戦より、散らかったタスクを整える日に向いています。ひとつ片づけるだけで、頭の霧が薄くなります。",
    luckyItem: "付箋",
    luckyColor: "スチールグレー",
    word: "整えた場所に集中が宿る。",
  },
  {
    id: "work-n-2",
    category: "work",
    rarity: "N",
    title: "午前の羅針盤",
    body: "最初の一時間の使い方が一日の手触りを決めます。簡単な仕事から始めると、自然に勢いが出ます。",
    luckyItem: "ブラックコーヒー",
    luckyColor: "ネイビー",
    word: "小さく始めて勝つ。",
  },
  {
    id: "work-n-3",
    category: "work",
    rarity: "N",
    title: "静かな歯車",
    body: "目立つ成果より、裏側の確認が評価につながります。誰も見ていない丁寧さが、後から効いてきます。",
    luckyItem: "クリアファイル",
    luckyColor: "ライトブルー",
    word: "地味な正確さは強い。",
  },
  {
    id: "work-r-1",
    category: "work",
    rarity: "R",
    title: "評価の小窓",
    body: "あなたの工夫に気づく人がいます。全部を説明しなくても、要点だけ見える形にすると伝わりやすいでしょう。",
    luckyItem: "短いメモ",
    luckyColor: "シアン",
    word: "成果は見せ方で目覚める。",
  },
  {
    id: "work-r-2",
    category: "work",
    rarity: "R",
    title: "締切の魔針",
    body: "時間の使い方に追い風があります。完璧を待つより、七割で一度出すことで流れが良くなります。",
    luckyItem: "タイマー",
    luckyColor: "インディゴ",
    word: "仮置きが突破口。",
  },
  {
    id: "work-r-3",
    category: "work",
    rarity: "R",
    title: "協力者の灯",
    body: "一人で抱えた作業に助けが入りやすい日です。頼る時は遠慮より、具体的な依頼が運を呼びます。",
    luckyItem: "チャットの下書き",
    luckyColor: "ミントブルー",
    word: "頼み方もスキルです。",
  },
  {
    id: "work-sr-1",
    category: "work",
    rarity: "SR",
    title: "昇格前夜の星",
    body: "次の役割に近づくサインがあります。少し難しい依頼ほど、あなたの器を広げる試練になりそうです。",
    luckyItem: "上質なノート",
    luckyColor: "サファイア",
    word: "背伸びの先に席がある。",
  },
  {
    id: "work-sr-2",
    category: "work",
    rarity: "SR",
    title: "ひらめきの祭壇",
    body: "散らばっていた情報が一つにつながります。今日は移動中や休憩中に出る案を逃さないでください。",
    luckyItem: "ボイスメモ",
    luckyColor: "ネオンブルー",
    word: "余白に答えが降りる。",
  },
  {
    id: "work-sr-3",
    category: "work",
    rarity: "SR",
    title: "隠れた才能",
    body: "当たり前にできることが、誰かには価値として映ります。自分の強みを軽く扱わないほど評価が伸びます。",
    luckyItem: "過去の資料",
    luckyColor: "ラピスラズリ",
    word: "普通にできることが武器。",
  },
  {
    id: "work-ssr-1",
    category: "work",
    rarity: "SSR",
    title: "運命案件 起動",
    body: "停滞していたプロジェクトが、近いうちに反転を始めます。違和感のある依頼ほど、未来の評価につながります。",
    luckyItem: "青いペン",
    luckyColor: "エレクトリックバイオレット",
    word: "難題は名札を変えた好機。",
  },
  {
    id: "work-ssr-2",
    category: "work",
    rarity: "SSR",
    title: "黒翼の抜擢",
    body: "見られていないと思った努力に光が当たります。急な相談や依頼には、できる範囲で前向きに応えて。",
    luckyItem: "腕時計",
    luckyColor: "ミッドナイトブルー",
    word: "準備済みの人に風が吹く。",
  },
  {
    id: "work-ssr-3",
    category: "work",
    rarity: "SSR",
    title: "戦略の王冠",
    body: "作業者から設計者へ意識を切り替えるタイミングです。全体像を一枚にまとめると、発言の重みが増します。",
    luckyItem: "マインドマップ",
    luckyColor: "シルバー",
    word: "俯瞰した瞬間、盤面が変わる。",
  },
  {
    id: "work-ur-1",
    category: "work",
    rarity: "UR",
    title: "禁断昇進 解放",
    body: "あなたの中で眠っていた役割が目を覚まします。選ばれるのを待つより、名乗り出ることで未来の肩書きが近づきます。",
    luckyItem: "黒革のノート",
    luckyColor: "虹鋼",
    word: "席は空く前に取りに行く。",
  },
  {
    id: "work-ur-2",
    category: "work",
    rarity: "UR",
    title: "未来職位の神託",
    body: "今の不満は、次のステージへの招待状です。変えたいことをひとつ言語化すると、運命が具体的に動き始めます。",
    luckyItem: "企画書のテンプレート",
    luckyColor: "オーロラブルー",
    word: "願望を仕様に変えて。",
  },
  {
    id: "work-ur-3",
    category: "work",
    rarity: "UR",
    title: "星導く転機",
    body: "これまで点だった経験が線になります。異なる場所で学んだことほど、今の仕事で希少な力になります。",
    luckyItem: "昔の名刺",
    luckyColor: "ギャラクシーパープル",
    word: "回り道が最短になる。",
  },
  {
    id: "relations-n-1",
    category: "relations",
    rarity: "N",
    title: "静かな境界線",
    body: "相手の機嫌を背負いすぎないことが大切です。やさしさは、少し距離を置いてもちゃんと伝わります。",
    luckyItem: "イヤホン",
    luckyColor: "セージグリーン",
    word: "近すぎない方が守れる関係もある。",
  },
  {
    id: "relations-n-2",
    category: "relations",
    rarity: "N",
    title: "挨拶の護符",
    body: "短い挨拶や反応が、空気をやわらかくします。難しい話をする前に、場の温度を整えると吉です。",
    luckyItem: "のど飴",
    luckyColor: "ペールグリーン",
    word: "最初の一言が結界になる。",
  },
  {
    id: "relations-n-3",
    category: "relations",
    rarity: "N",
    title: "透明な間合い",
    body: "今日は聞き役に回るほど信頼が増します。すぐ答えを出さなくても、相手は受け止められたと感じます。",
    luckyItem: "温かい飲み物",
    luckyColor: "スモークミント",
    word: "沈黙にも返事はある。",
  },
  {
    id: "relations-r-1",
    category: "relations",
    rarity: "R",
    title: "結び直しの糸",
    body: "少し気まずかった相手と、自然に空気を戻せる兆しがあります。大げさな謝罪より、普通の会話が効きます。",
    luckyItem: "共有できるお菓子",
    luckyColor: "ターコイズ",
    word: "日常が関係を修復する。",
  },
  {
    id: "relations-r-2",
    category: "relations",
    rarity: "R",
    title: "噂の濾過器",
    body: "人づての情報に振り回されやすい日です。判断は本人の言葉を聞いてからで十分です。",
    luckyItem: "水のボトル",
    luckyColor: "クリアブルー",
    word: "濁った話は寝かせて澄ます。",
  },
  {
    id: "relations-r-3",
    category: "relations",
    rarity: "R",
    title: "輪の外の星",
    body: "いつもの集まりから少し離れると、別の縁が見えます。無理に中心にいなくても、あなたの場所はあります。",
    luckyItem: "歩きやすい靴",
    luckyColor: "フォレスト",
    word: "外側にも居場所はある。",
  },
  {
    id: "relations-sr-1",
    category: "relations",
    rarity: "SR",
    title: "信頼の紋章",
    body: "あなたの誠実さが、静かに評価される時です。約束をひとつ守るだけで、関係の芯が強くなります。",
    luckyItem: "予定表",
    luckyColor: "エバーグリーン",
    word: "信頼は派手ではなく深い。",
  },
  {
    id: "relations-sr-2",
    category: "relations",
    rarity: "SR",
    title: "共鳴する沈黙",
    body: "言葉が少なくても通じる相手に救われそうです。説明しすぎないことで、逆に本音が届く場面があります。",
    luckyItem: "静かな席",
    luckyColor: "ブルーグリーン",
    word: "わかる人には短くていい。",
  },
  {
    id: "relations-sr-3",
    category: "relations",
    rarity: "SR",
    title: "橋渡しの月",
    body: "対立しているものの間に立てる日です。ただし全部を背負わず、できる範囲で言葉を整えてください。",
    luckyItem: "中立色の服",
    luckyColor: "ムーンミント",
    word: "橋は自分まで燃やさない。",
  },
  {
    id: "relations-ssr-1",
    category: "relations",
    rarity: "SSR",
    title: "縁環反転",
    body: "離れたと思った縁が、別の役割を持って戻ります。過去の印象だけで判断しないことが、良い展開を呼びます。",
    luckyItem: "古い連絡先",
    luckyColor: "オパールグリーン",
    word: "縁は形を変えて生きる。",
  },
  {
    id: "relations-ssr-2",
    category: "relations",
    rarity: "SSR",
    title: "真名を呼ぶ者",
    body: "あなたを正しく見てくれる人が現れます。気を遣いすぎて隠していた本音を、少しだけ出してみてください。",
    luckyItem: "名前入りのもの",
    luckyColor: "ジェイド",
    word: "理解は突然深くなる。",
  },
  {
    id: "relations-ssr-3",
    category: "relations",
    rarity: "SSR",
    title: "夜会の同盟",
    body: "同じ違和感を持つ人とつながれそうです。共感から始まる会話が、思った以上に強い味方を生みます。",
    luckyItem: "小さな差し入れ",
    luckyColor: "ブラックグリーン",
    word: "味方は静かに増える。",
  },
  {
    id: "relations-ur-1",
    category: "relations",
    rarity: "UR",
    title: "魂縁神託 解放",
    body: "あなたの人間関係に、選び直しの光が差します。合わない場所を手放すほど、本当に必要な縁が近づきます。",
    luckyItem: "白い糸",
    luckyColor: "虹緑",
    word: "縁は数ではなく響き。",
  },
  {
    id: "relations-ur-2",
    category: "relations",
    rarity: "UR",
    title: "盟友降臨",
    body: "長く続く味方との接点が生まれる兆しです。飾らない困りごとを共有すると、関係が一段深くなります。",
    luckyItem: "二人で分けるもの",
    luckyColor: "オーロラミント",
    word: "弱さを出せる相手は宝です。",
  },
  {
    id: "relations-ur-3",
    category: "relations",
    rarity: "UR",
    title: "結界破りの祝福",
    body: "苦手だと思っていた相手との間に、予想外の理解が生まれます。決めつけを一枚剥がすだけで、流れは変わります。",
    luckyItem: "透明な傘",
    luckyColor: "プリズムグリーン",
    word: "壁の向こうも同じ空です。",
  },
  {
    id: "abyss-n-1",
    category: "abyss",
    rarity: "N",
    title: "浅い裂け目",
    body: "少し気になる違和感は、すぐ消さずに眺めてください。答えを急がなければ、不安はただの合図になります。",
    luckyItem: "黒い石",
    luckyColor: "灰紫",
    word: "覗きすぎなければ戻れます。",
  },
  {
    id: "abyss-n-2",
    category: "abyss",
    rarity: "N",
    title: "影の栞",
    body: "忘れたふりをしていたことが、ふと浮かぶかもしれません。怖がらず、今日はメモだけして閉じておきましょう。",
    luckyItem: "栞",
    luckyColor: "チャコール",
    word: "閉じる力も魔法です。",
  },
  {
    id: "abyss-n-3",
    category: "abyss",
    rarity: "N",
    title: "夜更けのノイズ",
    body: "考えすぎるほど輪郭が歪む日です。結論を出すより、早めに休む方が深淵は静まります。",
    luckyItem: "アイマスク",
    luckyColor: "ダークネイビー",
    word: "夜の判断は朝に預けて。",
  },
  {
    id: "abyss-r-1",
    category: "abyss",
    rarity: "R",
    title: "歪んだ鏡",
    body: "人の言葉に、自分の恐れを重ねて見やすい日です。事実と想像を分けるだけで、影は少し薄くなります。",
    luckyItem: "曇り止めクロス",
    luckyColor: "スモークパープル",
    word: "鏡は時々、心を映す。",
  },
  {
    id: "abyss-r-2",
    category: "abyss",
    rarity: "R",
    title: "黒猫の通告",
    body: "避けていた選択肢が、妙に気になり始めます。すぐ選ばなくていいので、なぜ怖いのかだけ見てください。",
    luckyItem: "黒い靴下",
    luckyColor: "ミッドナイト",
    word: "恐れの裏には願いがある。",
  },
  {
    id: "abyss-r-3",
    category: "abyss",
    rarity: "R",
    title: "沈む星",
    body: "期待が一度下がることで、本当に欲しいものが残ります。諦めではなく、選別の時間です。",
    luckyItem: "苦いチョコ",
    luckyColor: "ディープブルー",
    word: "沈んだものだけが底を知る。",
  },
  {
    id: "abyss-sr-1",
    category: "abyss",
    rarity: "SR",
    title: "深層の呼び声",
    body: "理由なく惹かれる方向に、今のあなたを変えるヒントがあります。ただし一気に飛び込まず、入口だけ確かめて。",
    luckyItem: "古本",
    luckyColor: "ウルトラバイオレット",
    word: "呼ばれても、歩幅は選べる。",
  },
  {
    id: "abyss-sr-2",
    category: "abyss",
    rarity: "SR",
    title: "失われた王冠",
    body: "昔あきらめた誇りが戻りたがっています。誰かに認められる前に、自分の中で拾い上げてください。",
    luckyItem: "アンティーク調のもの",
    luckyColor: "古金",
    word: "落とした冠はまだ錆びていない。",
  },
  {
    id: "abyss-sr-3",
    category: "abyss",
    rarity: "SR",
    title: "禁句の箱",
    body: "言えずにいた本音が、形を変えて出てきます。ぶつけるのではなく、まず自分だけに正直になると安全です。",
    luckyItem: "鍵付きメモ",
    luckyColor: "ボルドーブラック",
    word: "言葉は封印にも解放にもなる。",
  },
  {
    id: "abyss-ssr-1",
    category: "abyss",
    rarity: "SSR",
    title: "深淵反転の刻",
    body: "避けていた影が、近いうちに力へ変わります。小さな違和感を見逃さないでください。それは変化の入口です。",
    luckyItem: "黒水晶",
    luckyColor: "禁紫",
    word: "影は向き合う者に従う。",
  },
  {
    id: "abyss-ssr-2",
    category: "abyss",
    rarity: "SSR",
    title: "月蝕の神託",
    body: "一度隠れたものが、別の姿で現れます。失ったと思った時間にも、まだ使える意味が残っています。",
    luckyItem: "月の画像",
    luckyColor: "エクリプス",
    word: "欠けた月ほど輪郭が鋭い。",
  },
  {
    id: "abyss-ssr-3",
    category: "abyss",
    rarity: "SSR",
    title: "虚無の祝祭",
    body: "空っぽに感じる場所へ、新しい欲望が入り込む気配があります。何もない日を、失敗と決めないでください。",
    luckyItem: "空の小瓶",
    luckyColor: "ブラックラベンダー",
    word: "虚無は次の器です。",
  },
  {
    id: "abyss-ur-1",
    category: "abyss",
    rarity: "UR",
    title: "禁断神託 解放",
    body: "あなたの選ばなかった未来が、深淵の底からもう一度扉を叩いています。偶然に見える出来事ほど、今は意味を持ちます。",
    luckyItem: "封印された手紙",
    luckyColor: "虹を帯びた漆黒",
    word: "戻れない場所から始まる未来がある。",
  },
  {
    id: "abyss-ur-2",
    category: "abyss",
    rarity: "UR",
    title: "虚星降臨",
    body: "まだ名前のない願いが、あなたの内側で形を持ち始めています。怖さは拒絶ではなく、変身前の震えです。",
    luckyItem: "星砂",
    luckyColor: "アビスレインボー",
    word: "名付けた瞬間、支配できる。",
  },
  {
    id: "abyss-ur-3",
    category: "abyss",
    rarity: "UR",
    title: "終末の白い扉",
    body: "終わりだと思っていた章の裏に、白紙のページがあります。壊れた予定ほど、今は神託に近い働きをします。",
    luckyItem: "白いカード",
    luckyColor: "終末白",
    word: "終わりは扉の別名です。",
  },
];

export function getCategory(id: GachaCategoryId) {
  return categories.find((category) => category.id === id) ?? categories[0];
}

export function pickFortune(category: GachaCategoryId, rarity: Rarity): FortuneResult {
  const pool = fortuneResults.filter((result) => result.category === category && result.rarity === rarity);
  return pool[Math.floor(Math.random() * pool.length)];
}
